# Generated by Django 2.1.1 on 2018-09-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_remove_blooddonationevent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Donor'), (2, 'Recipient'), (3, 'BloodBank'), (4, 'Hospital'), (5, 'LocalBody'), (6, 'Admin')], default=5),
        ),
    ]
