# Generated by Django 2.1.1 on 2018-10-13 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_auto_20180910_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], default='O+', max_length=20)),
                ('quantity', models.IntegerField()),
                ('reports', models.FileField(upload_to='')),
                ('anomaly', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.datetime(2018, 10, 13, 9, 49, 23, 575458))),
                ('request_quantity', models.IntegerField()),
                ('request_type', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], default='O+', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default='Sion', max_length=20),
        ),
        migrations.AddField(
            model_name='blood',
            name='blood_bank',
            field=models.ManyToManyField(default=1, to='roles.BloodBank'),
        ),
    ]
