# Generated by Django 2.1.1 on 2018-10-14 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_auto_20181013_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 10, 14, 22, 29, 3, 319531)),
        ),
    ]
