# Generated by Django 2.1.1 on 2018-10-14 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_auto_20181014_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 10, 14, 23, 36, 52, 269065)),
        ),
    ]
