# Generated by Django 2.1.2 on 2018-10-15 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_auto_20181014_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='localbodies',
            name='address',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='address',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='localbodies',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='localbodies',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='recipient',
            name='location',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 13, 18, 23, 674442)),
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='blooddonationevent',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 13, 18, 23, 672447)),
        ),
        migrations.AlterField(
            model_name='blooddonationevent',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.datetime(2018, 10, 15, 13, 18, 23, 674442)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Donor'), (2, 'Recipient'), (3, 'BloodBank'), (4, 'Hospital'), (5, 'LocalBody'), (6, 'Admin')], default=6),
        ),
    ]
